"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

IS_RENDER = os.getenv("RENDER") == "true"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY") or os.environ.get("SECRETKEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "false" if IS_RENDER else "true").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.100.148',
    '.onrender.com',
]
if render_host := os.getenv("RENDER_EXTERNAL_HOSTNAME"):
    ALLOWED_HOSTS.append(render_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'users',
    'corsheaders',

    'cloudinary_storage',
    'cloudinary',

    'anymail',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.PlatformSecurityMiddleware',
]

ROOT_URLCONF = 'project.urls'

CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://192.168.100.148:5173",
    "https://pno-amores.vercel.app",
]
if extra_csrf := os.getenv("CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS.extend(
        origin.strip() for origin in extra_csrf.split(",") if origin.strip()
    )
if render_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{render_host}")

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-user-token",
]
CORS_EXPOSE_HEADERS = [
    "content-disposition",
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _resolve_db_host(host):
    # Neon pooler connections leave search_path empty, which breaks migrations/DDL.
    if host and "-pooler" in host and os.getenv("USE_DB_POOLER", "").lower() != "true":
        host = host.replace("-pooler", "")
    return host

def _database_from_url(database_url):
    parsed = urlparse(database_url)
    query = parse_qs(parsed.query)
    host = _resolve_db_host(parsed.hostname or "")
    options = {'connect_timeout': 10}
    sslmode = query.get('sslmode', ['require'])[0]
    if sslmode:
        options['sslmode'] = sslmode
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': (parsed.path or '/').lstrip('/'),
        'USER': parsed.username,
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': host,
        'PORT': parsed.port or 5432,
        'OPTIONS': options,
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
    }


def _database_config():
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        return _database_from_url(database_url)

    # Prefer DB_* vars on Render/Linux; plain USER can conflict with the OS user.
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME") or os.getenv("NAME"),
        'USER': os.getenv("DB_USER") or os.getenv("PGUSER") or os.getenv("USER"),
        'PASSWORD': os.getenv("DB_PASSWORD") or os.getenv("PASSWORD"),
        'HOST': _resolve_db_host(os.getenv("DB_HOST") or os.getenv("HOST", "")),
        'PORT': os.getenv("DB_PORT", "5432"),
        'OPTIONS': {
            'connect_timeout': 10,
            'sslmode': 'require',
        },
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
    }

DATABASES = {
    'default': _database_config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUD_NAME'),
    'API_KEY': os.getenv('API_KEY'),
    'API_SECRET': os.getenv('API_SECRET')
}

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (for image uploads from applicants)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage" if IS_RENDER else "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# ── Email Configuration ────────────────────────────────────────────────────────────────
# ── Email Configuration (Gmail SMTP) ──────────────────────────────────────────
EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
EMAIL_HOST_USER= os.getenv("EMAIL_HOST_USER")
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', f'PNP-AMORES <{EMAIL_HOST_USER}>')

ANYMAIL = {
    "BREVO_API_KEY": os.getenv("BREVO_API_KEY"),
}

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}