# Generated by Django 6.0.1 on 2026-03-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_applicant_infos_user_name_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Recruiter', 'Recruiter')], default='recruiter', max_length=20),
        ),
    ]
