# Generated by Django 6.0.1 on 2026-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Recruiter', 'Recruiter')], default='Recruiter', max_length=20),
        ),
    ]
