# Generated by Django 6.0.1 on 2026-03-31 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_infos',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='cp_number',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='date_graduated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='height',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='latin_honor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='middle_initial',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='name_of_school',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='pag_ibig_number',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='phil_health_id_num',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='program',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='tribe_affiliated',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
