# Generated by Django 6.0.1 on 2026-03-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_applicant_infos_age_applicant_infos_cp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_infos',
            name='email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
