# Generated by Django 6.0.1 on 2026-03-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_applicant_infos_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_infos',
            name='latin_honor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
