# Generated by Django 6.0.1 on 2026-03-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_applicant_infos_latin_honor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_infos',
            name='pag_ibig_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='applicant_infos',
            name='phil_health_id_num',
            field=models.CharField(max_length=15),
        ),
    ]
