# Generated by Django 6.0.1 on 2026-03-31 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_applicant_infos_pag_ibig_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_infos',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
