# Generated by Django 6.0.1 on 2026-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_applicant_infos_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_infos',
            name='middle_initial',
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='middle_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
