# Generated by Django 6.0.1 on 2026-04-01 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_applicant_infos_middle_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_infos',
            name='date_graduated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
