# Generated by Django 6.0.1 on 2026-04-01 07:49

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_applicant_infos_date_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_infos',
            name='date_graduated',
            field=models.DateField(default=users.models.default_date),
        ),
    ]
