# Generated by Django 6.0.1 on 2026-04-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_applicant_infos_date_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_infos',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
