# Generated by Django 6.0.1 on 2026-04-02 06:28

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_applicant_infos_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_infos',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='track_code',
            field=models.CharField(default=users.models.generate_tracking_code, editable=False, max_length=20, unique=True),
        ),
    ]
