# Generated by Django 6.0.1 on 2026-04-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_applicant_infos_status_applicant_infos_track_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant_infos',
            old_name='track_code',
            new_name='tracking_code',
        ),
    ]
