# Generated by Django 6.0.1 on 2026-04-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_track_code_applicant_infos_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PSA', 'PSA Birth Certificate'), ('ELIGIBILITY', 'Eligibilities'), ('SCHOLASTIC', 'Scholastic Records (Diploma/OTR)'), ('CLEARANCE', 'Clearances')], max_length=20)),
                ('file', models.ImageField(upload_to='applicant_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.applicant_infos')),
            ],
        ),
    ]
