# Generated by Django 6.0.1 on 2026-04-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_applicant_infos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_infos',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
