# Generated by Django 6.0.1 on 2026-04-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_applicant_infos_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_infos',
            name='latin_honor',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_infos',
            name='tribe_affiliated',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
