# Generated by Django 6.0.1 on 2026-04-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='application_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='application_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
