# Generated by Django 6.0.1 on 2026-05-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_infos',
            name='status',
            field=models.CharField(choices=[('New Applicant', 'New Applicant'), ('Document Review', 'Document Review'), ('Initial Screening', 'Initial Screening'), ('Technical Interview', 'Technical Interview'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Body Mass Index', 'Body Mass Index'), ('Physical Agility Test', 'Physical Agility Test'), ('Conduct new (Psychological)', 'Conduct new (Psychological)'), ('Medical', 'Medical'), ('Drug Test', 'Drug Test'), ('Final Interview', 'Final Interview'), ('Oath Taking', 'Oath Taking')], default='New Applicant', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
