# Generated by Django 6.0.1 on 2026-05-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_applicant_infos_status_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_infos',
            name='bmi_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='bmi_result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='bmi_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='drug_test_result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='final_interview_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='medical_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='oath_taking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='pat_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='psychological_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
