# Generated by Django 6.0.1 on 2026-05-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_applicant_infos_bmi_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_infos',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant_infos',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
