# Generated by Django 6.0.1 on 2026-05-13 05:58

import django.db.models.deletion
import users.models
from django.db import migrations, models


def migrate_data(apps, schema_editor):
    OldApplicant = apps.get_model('users', 'Applicant_infos')
    NewApplicant = apps.get_model('users', 'Applicant')
    Application = apps.get_model('users', 'Application')
    Evaluation = apps.get_model('users', 'Evaluation')
    ApplicantDocument = apps.get_model('users', 'ApplicantDocument')
    AuditLog = apps.get_model('users', 'AuditLog')
    User = apps.get_model('users', 'User')

    for old in OldApplicant.objects.all():
        # 1. Create Applicant (Preserve the ID)
        new_applicant = NewApplicant.objects.create(
            id=old.id,
            first_name=old.firstname,
            last_name=old.lastname,
            middle_name=old.middle_name,
            age=old.age,
            email=old.email,
            contact_number=old.cp_number,
            program=old.program,
            date_graduated=old.date_graduated,
            name_of_school=old.name_of_school,
            latin_honor=old.latin_honor,
            pag_ibig_number=old.pag_ibig_number,
            phil_health_id_num=old.phil_health_id_num,
            height=old.height,
            tribe=old.tribe_affiliated,
        )
        NewApplicant.objects.filter(id=new_applicant.id).update(created_at=old.created_at)

        # 2. Create Application
        app = Application.objects.create(
            applicant=new_applicant,
            tracking_code=old.tracking_code,
            status=old.status,
            rejection_reason=old.rejection_reason,
            scheduled_date=old.scheduled_date,
            scheduled_time=old.scheduled_time,
            evaluation_remarks=old.evaluation_remarks,
            oath_taking_date=old.oath_taking_date,
        )
        Application.objects.filter(id=app.id).update(created_at=old.created_at)

        # 3. Create Evaluation
        Evaluation.objects.create(
            application=app,
            bmi_height=old.bmi_height,
            bmi_weight=old.bmi_weight,
            bmi_result=old.bmi_result,
            pat_score=old.pat_score,
            psychological_result=old.psychological_result,
            medical_result=old.medical_result,
            drug_test_result=old.drug_test_result,
            final_interview_score=old.final_interview_score,
        )
        
        # 4. Update Documents to point to the new Applicant model
        # The IDs are the same now, so we just need to ensure the pointers are valid.
        # ApplicantDocument.objects.filter(applicant_id=old.id).update(applicant_id=new_applicant.id)
        # Actually, since we preserved the ID, they are already "correct" in terms of values,
        # but the DB needs to know they are now pointing to the 'Applicant' table.
        # This is handled by the AlterField operation in the migration.

    # 5. Migrate Audit Logs
    for log in AuditLog.objects.all():
        username = getattr(log, 'user', None)
        if username:
            performer = User.objects.filter(username=username).first()
            log.performer = performer
            log.performer_name = username
            log.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_applicant_infos_evaluation_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('age', models.IntegerField(default=18, verbose_name='Age')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email Address')),
                ('contact_number', models.CharField(max_length=11, verbose_name='Contact Number')),
                ('program', models.CharField(max_length=100, verbose_name='Program/Course')),
                ('date_graduated', models.DateField(default=users.models.default_date, verbose_name='Date Graduated')),
                ('name_of_school', models.CharField(max_length=200, verbose_name='Name of School')),
                ('latin_honor', models.CharField(blank=True, default='N/A', max_length=50, null=True, verbose_name='Latin Honor')),
                ('pag_ibig_number', models.CharField(max_length=15, verbose_name='Pag-IBIG Number')),
                ('phil_health_id_num', models.CharField(max_length=15, verbose_name='PhilHealth ID')),
                ('height', models.CharField(max_length=10, verbose_name='Height')),
                ('tribe', models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Tribe Affiliation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Registered')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=users.models.generate_tracking_code, editable=False, max_length=20, unique=True, verbose_name='Tracking Code')),
                ('status', models.CharField(choices=[('New Applicant', 'New Applicant'), ('Document Review', 'Document Review'), ('Initial Screening', 'Initial Screening'), ('Technical Interview', 'Technical Interview'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Body Mass Index', 'Body Mass Index'), ('Physical Agility Test', 'Physical Agility Test'), ('Neuro Examination', 'Neuro Examination'), ('Medical', 'Medical'), ('Drug Test', 'Drug Test'), ('Final Interview', 'Final Interview'), ('Oath Taking', 'Oath Taking')], default='New Applicant', max_length=50, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Scheduled Time')),
                ('evaluation_remarks', models.TextField(blank=True, null=True, verbose_name='Evaluation Remarks')),
                ('oath_taking_date', models.DateField(blank=True, null=True, verbose_name='Oath Taking Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.applicant', verbose_name='Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi_height', models.FloatField(blank=True, null=True, verbose_name='BMI Height (m)')),
                ('bmi_weight', models.FloatField(blank=True, null=True, verbose_name='BMI Weight (kg)')),
                ('bmi_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='BMI Result')),
                ('pat_score', models.FloatField(blank=True, null=True, verbose_name='PAT Score')),
                ('psychological_result', models.TextField(blank=True, null=True, verbose_name='Psychological Result')),
                ('medical_result', models.TextField(blank=True, null=True, verbose_name='Medical Result')),
                ('drug_test_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='Drug Test Result')),
                ('final_interview_score', models.FloatField(blank=True, null=True, verbose_name='Final Interview Score')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='users.application', verbose_name='Application')),
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.user', verbose_name='Performer'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='performer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Performer Name (Fallback)'),
        ),
        
        # --- DATA MIGRATION START ---
        migrations.RunPython(migrate_data),
        # --- DATA MIGRATION END ---

        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='document_type',
            field=models.CharField(choices=[('PSA', 'PSA Birth Certificate'), ('ELIGIBILITY', 'Eligibilities'), ('SCHOLASTIC', 'Scholastic Records (Diploma/OTR)'), ('CLEARANCE', 'Clearances')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='file',
            field=models.ImageField(upload_to='applicant_docs/', verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='application_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='application_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='is_application_open',
            field=models.BooleanField(default=True, verbose_name='Is Application Open'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is Archived'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Recruiter', 'Recruiter')], default='Recruiter', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.applicant', verbose_name='Applicant'),
        ),
        migrations.DeleteModel(
            name='Applicant_infos',
        ),
    ]


