# Generated by Django 6.0.1 on 2026-05-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_applicant_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='pag_ibig_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Pag-IBIG Number'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phil_health_id_num',
            field=models.CharField(max_length=15, unique=True, verbose_name='PhilHealth ID'),
        ),
    ]
