# Generated by Django 6.0.1 on 2026-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_applicant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='batch',
            field=models.IntegerField(default=1, verbose_name='Batch Number'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='current_batch',
            field=models.IntegerField(default=1, verbose_name='Current Batch'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('New Applicant', 'New Applicant'), ('Document Review', 'Document Review'), ('Initial Screening', 'Initial Screening'), ('Technical Interview', 'Technical Interview'), ('Qualified', 'Qualified'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Body Mass Index', 'Body Mass Index'), ('Physical Agility Test', 'Physical Agility Test'), ('Neuro Examination', 'Neuro Examination'), ('Medical', 'Medical'), ('Drug Test', 'Drug Test'), ('Final Interview', 'Final Interview'), ('Oath Taking', 'Oath Taking')], default='New Applicant', max_length=50, verbose_name='Status'),
        ),
    ]
