# Generated by Django 6.0.2 on 2026-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_application_batch_systemsettings_current_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='document_type',
            field=models.CharField(choices=[('PSA', 'PSA Birth Certificate'), ('ELIGIBILITY', 'Eligibilities'), ('SCHOLASTIC', 'Scholastic Records (Diploma/OTR)'), ('CLEARANCE', 'Clearances'), ('PHOTO', '2x2 ID Photo')], max_length=20, verbose_name='Document Type'),
        ),
    ]
