# Generated by Django 6.0.2 on 2026-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_add_photo_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='document_type',
            field=models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('OTR', 'Official Transcript of Records (OTR)'), ('DIPLOMA', 'Diploma'), ('BRGY_CLEARANCE', 'Barangay Clearance'), ('POLICE_CLEARANCE', 'National Police Clearance'), ('PROS_CLEARANCE', "Prosecutor's Clearance"), ('NBI_CLEARANCE', 'NBI Clearance'), ('PRC', 'PRC License'), ('NAPOLCOM', 'Napolcom Entrance Rating'), ('PD907', 'PD907 (Honor Graduate)'), ('CS_PROF', 'CS Professional Eligibility'), ('PSA', 'PSA Birth Certificate'), ('ELIGIBILITY', 'Eligibilities'), ('SCHOLASTIC', 'Scholastic Records (Diploma/OTR)'), ('CLEARANCE', 'Clearances')], max_length=25, verbose_name='Document Type'),
        ),
    ]
