# Generated by Django 6.0.2 on 2026-07-05 03:36

from django.db import migrations, models
from django.db.models.fields import IntegerField


def remove_age_if_exists(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM information_schema.columns WHERE table_name='users_applicant' AND column_name='age'")
        if cursor.fetchone():
            schema_editor.execute('ALTER TABLE "users_applicant" DROP COLUMN "age"')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_expand_document_type_choices'),
    ]

    operations = [
        migrations.RunPython(remove_age_if_exists, migrations.RunPython.noop),
    ]
