# Generated by Django 6.0.2 on 2026-07-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_applicant_age'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='applicant',
                    name='age',
                ),
            ],
            database_operations=[],
        )
    ]
