# Generated by Django 6.0.2 on 2026-07-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_remove_applicant_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
    ]
