# Generated by Django 6.0.2 on 2026-07-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_applicant_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.TextField(default='N/A', verbose_name='Permanent Address'),
            preserve_default=False,
        ),
    ]
