# Generated by Django 6.0.2 on 2026-07-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
