# Generated by Django 6.0.2 on 2026-07-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='address',
        ),
        migrations.AddField(
            model_name='applicant',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barangay'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='city_municipality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City/Municipality'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
    ]
