# Generated by Django 6.0.2 on 2026-07-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_remove_applicant_address_applicant_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='street',
        ),
    ]
