# Generated by Django 6.0.2 on 2026-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='file',
            field=models.FileField(upload_to='applicant_docs/', verbose_name='Document File'),
        ),
    ]
