# Generated by Django 6.0.2 on 2026-07-19 15:27

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_applicantdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='applicant_docs/', verbose_name='Document File'),
        ),
    ]
