# Generated by Django 6.0.2 on 2026-07-20 14:42

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_applicantdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocument',
            name='ai_remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AI Remarks'),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='ai_verified',
            field=models.BooleanField(default=False, verbose_name='AI Verified'),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='ocr_text',
            field=models.TextField(blank=True, null=True, verbose_name='Extracted Text (OCR)'),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='applicant_docs/', verbose_name='Document File'),
        ),
    ]
