# Generated by Django 6.0.2 on 2026-07-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_applicantdocument_ai_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('New Applicant', 'New Applicant'), ('Technical Interview', 'Technical Interview'), ('Qualified', 'Qualified'), ('Accepted', 'Accepted'), ('Failed', 'Failed'), ('Body Mass Index', 'Body Mass Index'), ('Physical Agility Test', 'Physical Agility Test'), ('Neuro Examination', 'Neuro Examination'), ('Medical', 'Medical'), ('Drug Test', 'Drug Test'), ('Final Interview', 'Final Interview'), ('Oath Taking', 'Oath Taking')], default='New Applicant', max_length=50, verbose_name='Status'),
        ),
    ]
