# Generated by Django 6.0.2 on 2026-07-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_evaluation_pat_pushups_evaluation_pat_pushups_passed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Recruiter', 'Recruiter'), ('Interviewer', 'Interviewer')], default='Recruiter', max_length=20, verbose_name='Role'),
        ),
    ]
