# Generated by Django 6.0.2 on 2026-07-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_evaluation_fi_bearing_evaluation_fi_comprehension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocument',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
    ]
