# Generated by Django 6.0.2 on 2026-07-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('Administrator', 'Administrator'), ('Recruiter', 'Recruiter'), ('Interviewer', 'Interviewer')], default='Recruiter', max_length=20, verbose_name='Role'),
        ),
    ]
