# Generated by Django 6.0.2 on 2026-08-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_role_user_force_password_reset_user_is_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_reapplied',
            field=models.BooleanField(default=False),
        ),
    ]
