# Generated by Django 6.0.2 on 2026-08-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_applicant_is_reapplied'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_code', models.CharField(max_length=20, unique=True, verbose_name='Draft Code')),
                ('form_data', models.JSONField(verbose_name='Form Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
