# Generated by Django 6.0.2 on 2026-08-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_applicationdraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MasterLookup',
        ),
        migrations.DeleteModel(
            name='ApiKey',
        ),
    ]
