# Generated by Django 6.0.2 on 2026-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_remove_apikey_created_by_delete_masterlookup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('Administrator', 'Administrator'), ('Recruitment Personnel', 'Recruitment Personnel'), ('Recruitment Screening Committee (RSC)', 'Recruitment Screening Committee (RSC)')], default='Recruitment Personnel', max_length=50, verbose_name='Role'),
        ),
    ]
