# Generated by Django 6.0.2 on 2026-08-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('Administrator', 'Administrator'), ('Recruitment Personnel', 'Recruitment Personnel'), ('Recruitment Screening Committee (Interviewer)', 'Recruitment Screening Committee (Interviewer)')], default='Recruitment Personnel', max_length=50, verbose_name='Role'),
        ),
    ]
