# Generated by Django 6.0.2 on 2026-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_remove_evaluation_fi_bearing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='national_quota_regular',
            field=models.IntegerField(default=0, verbose_name='National Quota (Regular)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='regional_quota_attrition',
            field=models.IntegerField(default=0, verbose_name='Regional Quota (Attrition)'),
        ),
    ]
