# Generated by Django 6.0.2 on 2026-08-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_systemsettings_national_quota_regular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='national_quota_regular',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='regional_quota_attrition',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='national_quota',
            field=models.IntegerField(default=0, verbose_name='National Quota'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='national_quota_type',
            field=models.CharField(choices=[('Attrition', 'Attrition'), ('Regular', 'Regular')], default='Regular', max_length=20, verbose_name='National Quota Type'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='regional_quota',
            field=models.IntegerField(default=0, verbose_name='Regional Quota'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='regional_quota_type',
            field=models.CharField(choices=[('Attrition', 'Attrition'), ('Regular', 'Regular')], default='Attrition', max_length=20, verbose_name='Regional Quota Type'),
        ),
    ]
