# Generated by Django 6.0.2 on 2026-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_remove_systemsettings_national_quota_regular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='national_quota',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='national_quota_type',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='regional_quota',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='regional_quota_type',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='quota_category',
            field=models.CharField(choices=[('Attrition', 'Attrition'), ('Regular', 'Regular')], default='Attrition', max_length=20, verbose_name='Quota Category'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='quota_type',
            field=models.CharField(choices=[('Regional', 'Regional'), ('National', 'National')], default='Regional', max_length=20, verbose_name='Quota Type'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='quota_value',
            field=models.IntegerField(default=0, verbose_name='Quota Value'),
        ),
    ]
