# Generated by Django 6.0.2 on 2026-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_remove_systemsettings_national_quota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='quota_category',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='quota_value',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='quota_type',
            field=models.CharField(choices=[('Attrition', 'Attrition (Regional)'), ('Regular', 'Regular (National)')], default='Attrition', max_length=50, verbose_name='Type of Quota'),
        ),
    ]
