# Generated by Django 6.0.2 on 2026-09-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_evaluation_is_qualified_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='quota_type',
            field=models.CharField(blank=True, choices=[('Attrition', 'Attrition'), ('Regular', 'Regular')], max_length=50, null=True, verbose_name='Quota Type'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('New Applicant', 'New Applicant'), ('Qualified', 'Qualified'), ('Accepted', 'Accepted'), ('Failed', 'Failed'), ('Body Mass Index', 'Body Mass Index'), ('Physical Agility Test', 'Physical Agility Test'), ('Neuro Examination', 'Neuro Examination'), ('Medical', 'Medical'), ('Drug Test', 'Drug Test'), ('Complete Background Investigation', 'Complete Background Investigation'), ('Final Interview', 'Final Interview'), ('Oath Taking', 'Oath Taking')], default='New Applicant', max_length=50, verbose_name='Status'),
        ),
    ]
