# Generated by Django 6.0.2 on 2026-09-18 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_evaluationcriterion_remove_evaluation_fi_awareness_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcriterion',
            options={},
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='bmi_height',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='bmi_result',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='bmi_weight',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='drug_test_result',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='medical_result',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='pat_pushups',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='pat_pushups_passed',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='pat_run',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='pat_run_passed',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='pat_score',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='pat_situps',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='pat_situps_passed',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='psychological_result',
        ),
        migrations.AddField(
            model_name='evaluationcriterion',
            name='category',
            field=models.CharField(choices=[('Interview', 'Final Interview'), ('PAT', 'Physical Agility Test'), ('BMI', 'Body Mass Index'), ('Medical', 'Medical'), ('Neuro', 'Neuro Examination'), ('DrugTest', 'Drug Test')], default='Interview', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='text_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='max_score',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.evaluationcriterion'),
        ),
        migrations.AlterField(
            model_name='evaluationscore',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
