# Generated by Django 6.0.2 on 2026-09-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_remove_evaluation_evaluation_bmi_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluationCriterion',
            new_name='EvaluationCriteria',
        ),
    ]
