# Generated by Django 6.0.2 on 2026-09-19 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_evaluation_is_bmi_evaluated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_stage', models.CharField(max_length=100, verbose_name='Stage Failed')),
                ('reason', models.TextField(verbose_name='Rejection Reason')),
                ('failed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Failed')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='failed_record', to='users.application', verbose_name='Application')),
            ],
        ),
    ]
