# Generated by Django 6.0.2 on 2026-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_failedapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='quota_type',
            field=models.CharField(choices=[('Attrition', 'Attrition (Regional)'), ('Regular', 'Regular (National)')], default='Regular', max_length=50, verbose_name='Type of Quota'),
        ),
    ]
