# Generated by Django 6.0.2 on 2026-09-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_alter_systemsettings_quota_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barangay')),
                ('city_municipality', models.CharField(blank=True, max_length=100, null=True, verbose_name='City/Municipality')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profile', to='users.address', verbose_name='Address'),
        ),
    ]
