# Generated by Django 6.0.2 on 2026-09-20 11:40

from django.db import migrations


def migrate_addresses(apps, schema_editor):
    Applicant = apps.get_model('users', 'Applicant')
    Address = apps.get_model('users', 'Address')
    
    for applicant in Applicant.objects.all():
        address = Address.objects.create(
            barangay=applicant.barangay,
            city_municipality=applicant.city_municipality,
            province=applicant.province,
            zip_code=applicant.zip_code
        )
        applicant.address = address
        applicant.save(update_fields=['address'])

def reverse_migrate_addresses(apps, schema_editor):
    # To reverse, we can't easily put it back unless we have the fields on Applicant.
    # We will just pass since we can't do much if the fields are going to be deleted in the next migration anyway.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_address_applicant_address'),
    ]

    operations = [
        migrations.RunPython(migrate_addresses, reverse_migrate_addresses),
    ]
