# Generated by Django 6.0.2 on 2026-09-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_migrate_address_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='city_municipality',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='province',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='zip_code',
        ),
    ]
