# Generated by Django 6.0.2 on 2026-09-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_remove_applicant_barangay_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSetting',
        ),
    ]
