# Generated by Django 6.0.2 on 2026-09-20 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_delete_globalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='evaluating_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Evaluating By'),
        ),
        migrations.AddField(
            model_name='application',
            name='evaluation_lock_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Evaluation Lock Time'),
        ),
    ]
