# Generated by Django 6.0.2 on 2026-09-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_application_evaluating_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('NEW_APPLICANT', 'New Applicant'), ('EVALUATION', 'Evaluation')], max_length=50, verbose_name='Notification Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
