# Generated by Django 6.0.2 on 2026-09-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_systemnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_APPLICANT', 'New Applicant'), ('EVALUATION', 'Evaluation'), ('SCHEDULED', 'Scheduled')], max_length=50, verbose_name='Notification Type'),
        ),
    ]
